version: 2
jobs:
        build:
                docker:
                        - image: circleci/openjdk:8-jdk

                working_directory: ~/repo

                steps:
                        - checkout
                        - run: gradle check
                        - run: gradle jacocoTestReport
                        - run: mkdir -p test-results/common
                        - run: mkdir -p test-results/service
                        - run: mkdir -p test-results/webapp
                        - run: cp common/build/test-results/test/*.xml test-results/common
                        - run: cp webapp/build/test-results/test/*.xml test-results/service
                        - run: cp webapp/build/test-results/test/*.xml test-results/webapp
                        - store_test_results:
                            path: test-results
                        - store_artifacts:
                            path: common/build/reports
                        - store_artifacts:
                            path: service/build/reports
                        - store_artifacts:
                            path: webapp/build/reports

